version: "3.7"
services:
  email-relay:
    image: docker-sio-releases.seikatsu.io/email-relay:latest
    container_name: email-relay
    restart: always
    environment:
      - MAIL_USER=mail-user-login
      - MAIL_PASS=mail-pass-login
    networks:
      dockerized:
        aliases:
          - email-relay.docker.local
networks:
  dockerized:
    external: true
